# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeEnvelope_lb <- function(array, constraint) {
    .Call(`_profileslib_computeEnvelope_lb`, array, constraint)
}

LB_Keogh_lb <- function(candidateArray, upperBound, lowerBound) {
    .Call(`_profileslib_LB_Keogh_lb`, candidateArray, upperBound, lowerBound)
}

LB_Improved <- function(candidateArray, queryArray, ubQuery, lbQuery, windowSize) {
    .Call(`_profileslib_LB_Improved`, candidateArray, queryArray, ubQuery, lbQuery, windowSize)
}

computeEnvelope <- function(array, constraint) {
    .Call(`_profileslib_computeEnvelope`, array, constraint)
}

LB_Keogh2 <- function(candidateArray, upperBound, lowerBound) {
    .Call(`_profileslib_LB_Keogh2`, candidateArray, upperBound, lowerBound)
}

LB_Keogh <- function(candidateArray, upperBound, lowerBound) {
    .Call(`_profileslib_LB_Keogh`, candidateArray, upperBound, lowerBound)
}

readSurFile <- function(path) {
    .Call(`_profileslib_readSurFile`, path)
}

